let mdTemplateSentences = [
    "# Don't Know What to do?",
    "",
    "[Abstract area], simple words for the most important",
    "",
    "## Keywords",
    "",
    "[Languages], [Packages], [Aims]",
    "",
    "## Method",
    "",
    "[Method area], lots of things.",
    "",
    "What have you done?",
    "",
    "How does it work?",
    "",
    "Got some thinking?",
    "",
    "## Example Code",
    "",
    "```[language]",
    "// An excellent code example",
    "```",
    "",
    "Have a good day.",
];

let mdTemplate = mdTemplateSentences.join("\n");